### ISSUE TITLE
Crashes due to stack allocation of multidimensional arrays

### ISSUE THREAD

**Issue by erichoracek** [khanlou/NSArray-LongestCommonSubsequence#4]
We were getting some crashes (`SIGBUS`) in this code due to the stack allocation of the `lengths` multidimensional array. We switched over to using a `malloc`'d multidimensional array and the crashes have gone away. Thoughts on migrating this repo to that approach?

**Comment by khanlou** [comment]
totally open to it, feel free to make a PR!

**Comment by konstantinpavlikhin** [comment]
This issue is fixed in https://github.com/khanlou/NSArray-LongestCommonSubsequence/pull/5
